### ISSUE TITLE
Automatic download and processing of relevant grib data given input parameters.

### ISSUE THREAD

**Issue by kg4sgp** [kg4sgp/habsim#6]
We could (should imo) download relevant GFS GRIB data given input parameters. In this way we could easily do predictions on future times and have the program fetch the needed data to perform the simulation.

These would include:
* Launch Location
* Launch Time

**Comment by relrod** [comment]
I'm still not convinced this should be part of the habsim library. I think the habsim library should do things related to doing HAB sims. The CSV parser, even, should probably in theory be its own library, but alas.

It's ultimately your decision/library, but I think this crosses over the boundary of separation of concerns. You're going to have to pull in an HTTP client, and as an end user, if I saw that as a dependency here I'd be a little skeptical.

It is my opinion that anyone using the library should pass in the wind data however they want (and in fact, we should decouple the `CSVParser` types from the `HABSim` modules and introduce a `WindData` type or similar that includes the information we need for processing. Then the `CSVParser` module should target that (so our input to `sim` would be `HM.HashMap Key WindData` instead of `HM.HashMap Key GribLine`).

Maybe someone wants to use wind data from some other system that isn't from NOAA NCEI. In that case, they couldn't care less about our ability to pull from NOAA, and now we've forced them to install an HTTP client they'll never use.

JMHO.

**Comment by kg4sgp** [comment]
I do agree with you on that. I'd like habsim to be as agnostic as possible to the data input. It could be up to another program to present wind data to the program in a way that it understands. I think towards this end it would be right to move the CSV parser to its own library. I guess I'll go ahead and close this out.
